name: victoria
favicon: null
layout_spectrum: 0.28105670493096113
typography_spectrum: 0.744609881658107
title: Victoria Butterfly
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.12471616896800697
  lightness: 0.03496538661420345
  saturation: 0.820226144278422
  rhythmicContrast: 0.9071136764250696
purpose: []
